### ISSUE TITLE
Really Thanks to this!

### ISSUE THREAD

**Issue by ghost** [skx/gobasic#115]
Very great project. Basic language is lightweight and good to implement in my application! thanks

**Comment by skx** [comment]
> Very great project. 

I'm glad it is useful, I had a lot of fun writing it.

> Can I add function to call system call

If you could be more specific I could answer better.

Do you mean something like `system( "/bin/ls" )`, or something else?

You can register your own built-in functions pretty easily - see the `pokeFunction`, for example, in the [embedded example](https://github.com/skx/gobasic/blob/master/embed/main.go).
