### ISSUE TITLE
Conditionals Seem Limited

### ISSUE THREAD

**Issue by krschwab** [skx/gobasic#42]
This works as expected:
` IF 1=1 THEN PRINT "TEST"   `
This, however, fails
```
 IF 1+1 THEN PRINT "TEST"
 Error running program:
       Line  : factor() - unhandled token: Token{Type:PRINT Value:PRINT}
```

It seems to work fine in other basic interpreters I tried.

**Comment by skx** [comment]
Currently the format is:

    IF [CMP] THEN [STATEMENT]  (ELSE [STATEMENT])

The CMP operator can be:

* 1 = 2
* 1 <> 3
* 1 < 3
* 3 <= 5
* 4 > 4
* 4 >= 5

Your program is trying to do a boolean test, that could be added, but isn't expected to work right now.

**Comment by skx** [comment]
(The error you get is not great, it tried to parse the expression, jumping foward, and it went too far.)

**Comment by krschwab** [comment]
Got it.  I suppose I can just convert to   "IF (WHATEVER)>0" so it's not a barrier.
